---
title: "Dog_pupil_mimicry_Tobii"
author: "Lucrezia Lonardo"
date: "2024-02-28"
output: html_document
---
## Load packages
```{r }
#rm(list=ls())
library(tidyverse)
```

## Load raw data

```{r}
raw.data<-
  read_tsv("./data/Dog_pupil_mimicry_06_03_2024_AOI_based_raw_data.tsv") %>%
  mutate(Recording=as.factor(Recording)) %>%
  mutate(Participant=as.factor(Participant)) %>%
  mutate(Timeline=as.factor(Timeline)) %>%
  filter(Recording!="Recording56" & Recording!="Recording58" & Recording!="Recording60" & Recording!="Recording71" & Recording!="Recording107" & Recording!="Recording119" & Recording!="Recording156" & Recording!="Recording158" & Recording!="Recording160" & Recording!="Recording165" &  Recording!="Recording170" &  Recording!="Recording172" & Recording!="Recording177" & Recording!="Recording175") # Sessions to be excluded (if not already excluded from project) as they were collected again with lower data loss
```


```{r}
#figure out which trials to filter out, because they were repeated with lower data loss
trials.to.exclude<-c( 
which(raw.data$Recording=="Recording51" & raw.data$TOI=="d14-constr"),
which(raw.data$Recording=="Recording51" & raw.data$TOI=="h07-dilating"),
which(raw.data$Recording=="Recording52" & raw.data$TOI=="d03-dilating"),
which(raw.data$Recording=="Recording140" & raw.data$TOI=="d14-dilating"),
which(raw.data$Recording=="Recording141" & raw.data$TOI=="b11-constr"),
which(raw.data$Recording=="Recording141" & raw.data$TOI=="b10-dilating"),
which(raw.data$Recording=="Recording87" & raw.data$TOI=="b09-constr"),
which(raw.data$Recording=="Recording87" & raw.data$TOI=="h13-constr"),
which(raw.data$Recording=="Recording87" & raw.data$TOI=="h15-constr"),
which(raw.data$Recording=="Recording87" & raw.data$TOI=="b05-constr"),
which(raw.data$Recording=="Recording88" & raw.data$TOI=="b01-dilating"),
which(raw.data$Recording=="Recording88" & raw.data$TOI=="b03-constr"),
which(raw.data$Recording=="Recording139" & raw.data$TOI=="d03-constr"),
which(raw.data$Recording=="Recording159" & raw.data$TOI=="b06-constr"),
which(raw.data$Recording=="Recording214" & (raw.data$TOI=="h06-dilating" | raw.data$TOI=="b03-dilating")))


raw.data<-raw.data %>%  filter(!row_number() %in% trials.to.exclude)
  

raw.data.toi<-raw.data %>% 
  filter(TOI!="Entire Recording") %>% 
  droplevels() %>% 
  mutate(condition=ifelse(grepl("constr", TOI), "constricting", ifelse(grepl("dilating", TOI), "dilating", "grey_screen")))
```

## Explore data

```{r}
str(raw.data.toi)
levels(as.factor(raw.data.toi$Recording))
table(raw.data.toi$Participant, raw.data.toi$Recording)
levels(as.factor(raw.data.toi$TOI))
levels(as.factor(raw.data.toi$Timeline))

#check how many trials were collected with each dog
raw.data.toi.trials<-raw.data.toi %>% 
  filter(TOI!="grey_screen") %>% 
#mutate(N_trials_collected=count(Participant)) alternative to what is below
  group_by(Participant) %>% 
  summarise(N_trials_collected=n())
```
##Individual checks on repetion of sessions

####Kaije
```{r}
#check how many trials per dog
raw.data.toi.trials.kaije<-raw.data.toi %>% 
  filter(TOI!="grey_screen") %>% 
  filter(Participant=="kaije") %>% 
  droplevels()
length(raw.data.toi.trials.kaije$TOI) #Kaije has 95 trials (if > than actually collected, it means some sessions were repeated -> select the trials with lower data loss)

levels(as.factor(raw.data.toi.trials.kaije$TOI)) #which videos did the dog see?
  #mutate(N_trials_collected=count(Participant))
  # group_by(Participant) %>% 
  # summarise(N_trials_collected=n())

raw.data.toi.trials.kaije$TOI
#which trials are duplicates?
which(duplicated(raw.data.toi.trials.kaije$TOI)==TRUE)
```

#### Noodle
```{r}
#check how many trials per dog
raw.data.toi.trials.noodle<-raw.data.toi %>% 
  filter(TOI!="grey_screen") %>% 
  filter(Participant=="Noodle") %>% 
  droplevels()
length(raw.data.toi.trials.noodle$TOI) #Noodle has 93 trials (if more than actually collected, it means some sessions were repeated and I need to select the trials with lower data loss)

#which videos did the dog see?
levels(as.factor(raw.data.toi.trials.noodle$TOI)) 

# raw.data.toi.trials.noodle$TOI
# #which trials are duplicates?
# which(duplicated(raw.data.toi.trials.noodle$TOI)==TRUE)
```
#### Pepe
```{r}
#check how many trials per dog
raw.data.toi.trials.pepe<-raw.data.toi %>% 
  filter(TOI!="grey_screen") %>% 
  filter(Participant=="Pepe") %>% 
  droplevels()
length(raw.data.toi.trials.pepe$TOI) #Pepe has 42 trials (if more than actually collected, it means some sessions were repeated and I need to select the trials with lower data loss)

#which videos did the dog see?
levels(as.factor(raw.data.toi.trials.pepe$TOI)) 

```
#### Barney
```{r}
#check how many trials per dog
raw.data.toi.trials.barney<-raw.data.toi %>% 
  filter(TOI!="grey_screen") %>% 
  filter(Participant=="Barney") %>% 
  droplevels()
length(raw.data.toi.trials.barney$TOI) #Barney has 71 trials (if more than actually collected, it means some sessions were repeated and I need to select the trials with lower data loss)

#which videos did the dog see?
levels(as.factor(raw.data.toi.trials.barney$TOI)) 

```

##calculate % tracked (i.e., detected) gaze for each trial. Using the data with the Tobii "Fixation" gaze filter and the Total duration of fixations
```{r}
tracked.gaze.data.raw<-raw.data.toi %>% 
  filter(TOI!="grey_screen") %>% 
  mutate(percent_tracked_gaze=(Total_duration_of_fixations/Duration_of_interval)*100) %>% 
  mutate(percent_tracked_glances=(Total_duration_of_Glances/Duration_of_interval)*100)

#using glances instead of fixations results in the gaze being detected for longer
summary(tracked.gaze.data.raw$percent_tracked_gaze)
summary(tracked.gaze.data.raw$percent_tracked_glances)
sum(tracked.gaze.data.raw$percent_tracked_gaze<tracked.gaze.data.raw$percent_tracked_glances)
sum(tracked.gaze.data.raw$percent_tracked_gaze>tracked.gaze.data.raw$percent_tracked_glances)
sum(tracked.gaze.data.raw$percent_tracked_gaze==tracked.gaze.data.raw$percent_tracked_glances)

#potentially replace Total_duration_of_fixations with Total_duration_of_Glances.
#However for now I continue with fixations (the more conservative measure)

#only select relevant columns
tracked.gaze.data.raw.red<-tracked.gaze.data.raw %>% 
  select(c(Recording:Media, Average_pupil_diameter, Total_duration_of_Glances, condition, percent_tracked_gaze, percent_tracked_glances))
  
#Trials to be excluded
##gaze
tracked.gaze.data.raw.red.to.be.excluded<-tracked.gaze.data.raw.red %>% 
group_by(Participant) %>% 
summarise(percent_trials_excluded=sum(percent_tracked_gaze<50)/length(percent_tracked_gaze))

##glances
tracked.glances.data.red.to.be.excluded<-tracked.gaze.data.raw.red %>% 
group_by(Participant) %>% 
summarise(percent_trials_excluded=sum(percent_tracked_glances<50)/length(percent_tracked_glances))
```

###check if there are repeated sessions, to only keep trials with higher % tracked gaze 
```{r}
#Kaije
tracked.gaze.data.raw.red.kaije<-tracked.gaze.data.raw.red %>% 
  filter(Participant=="kaije")
which(duplicated(tracked.gaze.data.raw.red.kaije$TOI)==TRUE)

#Noodle
tracked.gaze.data.raw.red.noodle<-tracked.gaze.data.raw.red %>% 
  filter(Participant=="Noodle")
which(duplicated(tracked.gaze.data.raw.red.noodle$TOI)==TRUE)

#Pepe
tracked.gaze.data.raw.red.pepe<-tracked.gaze.data.raw.red %>% 
  filter(Participant=="Pepe")
which(duplicated(tracked.gaze.data.raw.red.pepe$TOI)==TRUE)

#Messi
tracked.gaze.data.raw.red.messi<-tracked.gaze.data.raw.red %>% 
  filter(Participant=="Messi")
which(duplicated(tracked.gaze.data.raw.red.messi$TOI)==TRUE)

#Barney
tracked.gaze.data.raw.red.barney<-tracked.gaze.data.raw.red %>% 
  filter(Participant=="Barney")
which(duplicated(tracked.gaze.data.raw.red.barney$TOI)==TRUE)
```


```{r}
####check which trials should be repeated for each dog

#Barney
to.be.repeated.raw.raw.Barney<-tracked.gaze.data.raw.red %>% 
filter(percent_tracked_gaze<50) %>% 
filter(Participant=="Barney")

#Messi
to.be.repeated.raw.Messi<-tracked.gaze.data.raw.red %>% 
filter(percent_tracked_gaze<50) %>% 
filter(Participant=="Messi")

#Kaije
to.be.repeated.raw.Kaije<-tracked.gaze.data.raw.red %>% 
filter(percent_tracked_gaze<50) %>% 
filter(Participant=="kaije")

#Noodle
to.be.repeated.raw.Noodle<-tracked.gaze.data.raw.red %>% 
filter(percent_tracked_gaze<50) %>% 
filter(Participant=="Noodle")

#Pepe
to.be.repeated.raw.Pepe<-tracked.gaze.data.raw.red %>% 
filter(percent_tracked_gaze<50) %>% 
filter(Participant=="Pepe")

```

