---
title: "Data_Export_Tobii"
author: "Lucrezia Lonardo"
date: "2024-03-25"
output: html_document
---

## Load packages and workspace
```{r }
rm(list=ls())
library(tidyverse)
#load("~/GitHub/dog_pupil_mimicry/workspaces/Tobii_data_export_workspace.RData")
#LL: Create here a parquet version of the data export file because it is too large for Github:


#for now I'm saving the data export in Eye-tracker/pupil mimicry/analyses_Tobii
```

## Load data

```{r}
#Load data with Tobii "Fixation" gaze filter and pupil "noise reduction" filter

#Make Parquet!
#all.data <- read_tsv("./data/Data_export_23_3_2024.tsv") 
all.data <- read_tsv("C:/Users/lonardol/Desktop/Eye-tracker/pupil_mimicry/analyses_Tobii/Data_export_gaze_filter_fixation_10_04_2024.tsv")

#Raw data
#raw.data<-read_tsv("C:/Users/lonardol/Desktop/Eye-tracker/pupil_mimicry/analyses_Tobii/Data_export_raw_data_10_04_2024.tsv")

names(all.data) <- gsub(" ", "_", names(all.data)) #replace spaces in column names with underscores

all.data<- all.data %>% 
  mutate(Recording_name = as.factor(Recording_name)) %>% 
  filter(Recording_name!= "Recording48" & Recording_name!="Recording55" & Recording_name!="Recording56" & Recording_name!="Recording57" & Recording_name!="Recording58" & Recording_name!="Recording60" & 
Recording_name!="Recording71" & Recording_name!="Recording72" & Recording_name!="Recording74" & 
Recording_name!="Recording75" & Recording_name!="Recording77" & Recording_name!="Recording78" & 
Recording_name!="Recording80" & Recording_name!="Recording81" & Recording_name!="Recording107" & Recording_name!="Recording108" & Recording_name!="Recording109" & Recording_name!="Recording119" & Recording_name!="Recording124" & Recording_name!="Recording125" & Recording_name!="Recording126" & Recording_name!="Recording127" & Recording_name!="Recording128" & Recording_name!="Recording131" & Recording_name!="Recording156" & Recording_name!="Recording158" & Recording_name!="Recording160" & Recording_name!="Recording161" & Recording_name!="Recording162" & Recording_name!="Recording164" & Recording_name!="Recording165" & Recording_name!="Recording170" & Recording_name!="Recording172" & Recording_name!="Recording175" & Recording_name!="Recording177" & Recording_name!="Recording180" & Recording_name!="Recording189" & Recording_name!="Recording193" & Recording_name!="Recording194" & Recording_name!="Recording195" & Recording_name!="Recording210" & Recording_name!="Recording221" &  Recording_name!="Recording244" & Recording_name!="Recording231" & Recording_name!="Recording248" & Recording_name!="Recording251" & Recording_name!="Recording252" & Recording_name!="Recording259" & Recording_name!="Recording260" & Recording_name!="Recording299" & Recording_name!="Recording305" & Recording_name!="Recording307" & Recording_name!="Recording310" ) # Sessions to be excluded (if not already excluded from project) as they were collected again with lower data loss
```

## Explore data

```{r}
str(all.data)
summary(all.data)

levels(as.factor(all.data$Event))
levels(as.factor(all.data$Event_value))
levels(as.factor(all.data$Presented_Media_name))
levels(as.factor(all.data$Presented_Stimulus_name))
```


```{r}
# Calculate mean calibration accuracy per each dog 

## Pepe
pepe_data <- all.data[all.data$Participant_name == "Pepe", ]
#Select average calibration accuracy in mm from the filtered dataframe
pepe_cal_data <- pepe_data[, 17]
summary(pepe_cal_data) #mean 1799 mm

# Barney
barney_data <- all.data[all.data$Participant_name == "Barney", ]
#Select average calibration accuracy in mm from the filtered dataframe
barney_cal_data <- barney_data[, 17]
summary(barney_cal_data) # mean  802.7 mm

# Messi
messi_data <- all.data[all.data$Participant_name == "Messi", ]
#Select average calibration accuracy in mm from the filtered dataframe
messi_cal_data <- messi_data[, 17]
summary(messi_cal_data) # mean 1313 mm

# Noodle
noodle_data <- all.data[all.data$Participant_name == "Noodle", ]
#Select average calibration accuracy in mm from the filtered dataframe
noodle_cal_data <- noodle_data[, 17]
summary(noodle_cal_data) # 578 mm

# Kaije
kaije_data <- all.data[all.data$Participant_name == "Kaije", ]
#Select average calibration accuracy in mm from the filtered dataframe
kaije_cal_data <- kaije_data[, 17]
summary(kaije_cal_data)

# Jazz
jazz_data <- all.data[all.data$Participant_name == "Jazz", ]
#Select average calibration accuracy in mm from the filtered dataframe
jazz_cal_data <-jazz_data[, 17]
summary(jazz_cal_data)





```

## Subsetting the data to only the time in which videos or grey screens were presented


```{r}
stim.data <- all.data %>%
  filter(grepl("constr", Presented_Media_name) | grepl("dilating", Presented_Media_name) | grepl("grey_screen", Presented_Media_name)) 


levels(as.factor(stim.data$Event_value))
summary(as.factor(stim.data$Event_value))
summary(as.factor(stim.data$Presented_Media_name))
summary(as.factor(all.data$Event_value))

                           

stim.data<- stim.data %>% mutate(condition=ifelse(grepl("constr", Event_value), "constricting", ifelse(grepl("dilating", Event_value), "dilating", "grey_screen")))

summary(as.factor(stim.data$condition))
```
## Check # of trials with each dog
```{r}

```

##For each dog, calculate percent tracked gaze
```{r}

```


