---
title: "Dog_pupil_mimicry_Tobii"
author: "Lucrezia Lonardo"
date: "2024-02-28"
output: html_document
---
## Load packages
```{r }
rm(list=ls())
library(tidyverse)
load("~/GitHub/dog_pupil_mimicry/workspaces/Tobii_workspace.RData")
```

## Load data

```{r}
#Load data with Tobii "Fixation" gaze filter and pupil "noise reduction" filter

all.data<-
  read_tsv("./data/Dog_pupil_mimicry_10_04_2024_AOI_based_gazefilterfixation_incl_glance.tsv") %>% 
  mutate(Recording=as.factor(Recording)) %>% 
  mutate(Participant=as.factor(Participant)) %>% 
  mutate(Timeline=as.factor(Timeline)) %>% 
  filter(Recording!="Recording48" & Recording!="Recording55" & Recording!="Recording56" & Recording!="Recording57" & Recording!="Recording58" & Recording!="Recording60" & Recording!="Recording68" & Recording!="Recording69" & Recording!="Recording70" & Recording!="Recording71" & Recording!="Recording72" & Recording!="Recording74" & Recording!="Recording75" & Recording!="Recording77" & Recording!="Recording78" & Recording!="Recording80" & Recording!="Recording81" & Recording!="Recording101" & Recording!="Recording105" & Recording!="Recording107" & Recording!="Recording108" & Recording!="Recording109" & Recording!="Recording119" & Recording!="Recording121" & Recording!="Recording124" & Recording!="Recording125" & Recording!="Recording126" & Recording!="Recording127" & Recording!="Recording128" & Recording!="Recording131" & Recording!="Recording137" & Recording!="Recording156" & Recording!="Recording158" & Recording!="Recording160" & Recording!="Recording161" & Recording!="Recording162" & Recording!="Recording164" & Recording!="Recording165" & Recording!="Recording170" & Recording!="Recording172" & Recording!="Recording175" & Recording!="Recording177" & Recording!="Recording180" & Recording!="Recording188" & Recording!="Recording189" & Recording!="Recording193" & Recording!="Recording194" & Recording!="Recording195" & Recording!="Recording210" & Recording!="Recording221" & Recording!="Recording244" & Recording!="Recording231" & Recording!="Recording248" & Recording!="Recording251" & Recording!="Recording252" & Recording!="Recording259" & Recording!="Recording260" & Recording!="Recording299" & Recording!="Recording305" & Recording!="Recording307" & Recording!="Recording310" & Recording!="Recording348" & Recording!="Recording349" & Recording!="Recording350" & Recording!="Recording351" & Recording!="Recording352" & Recording!="Recording353" & Recording!="Recording354" & Recording!="Recording356" & Recording!="Recording357" & Recording!="Recording358" & Recording!="Recording359" & Recording!="Recording360" & Recording!="Recording362" & Recording!="Recording363" & Recording!="Recording372" & Recording!="Recording359" & Recording!="Recording369" & Recording!="Recording393") %>% # Sessions to be excluded (if not already excluded from project) as they were collected again with lower data loss
droplevels()
```

```{r}
#figure out which trials to filter out, because they were repeated with lower data loss
trials.to.exclude<-c( 
which(all.data$Recording=="Recording52" & all.data$TOI=="d03-dilating"),
which(all.data$Recording=="Recording53" & all.data$TOI=="h08-dilating"),
which(all.data$Recording=="Recording61" & all.data$TOI=="b03-dilating"),
which(all.data$Recording=="Recording159" & all.data$TOI=="b06-constr"),
which(all.data$Recording=="Recording116" & all.data$TOI=="h14-constr"),
which(all.data$Recording=="Recording140" & all.data$TOI=="d14-dilating"),
which(all.data$Recording=="Recording196" & all.data$TOI=="b07-constr"),
which(all.data$Recording=="Recording286" & all.data$TOI=="b08-dilating"),
which(all.data$Recording=="Recording211" & all.data$TOI=="d02-constr"),
which(all.data$Recording=="Recording254" & all.data$TOI=="h15-dilating"),
which(all.data$Recording=="Recording280" & all.data$TOI=="h00-dilating"),
which(all.data$Recording=="Recording247" & all.data$TOI=="h08-dilating"),
which(all.data$Recording=="Recording250" & all.data$TOI=="h02-constr"),
which(all.data$Recording=="Recording164" & all.data$TOI=="d07-dilating"),
which(all.data$Recording=="Recording250" & all.data$TOI=="b05-constr"),
which(all.data$Recording=="Recording110" & all.data$TOI=="d10-dilating"),
which(all.data$Recording=="Recording288" & all.data$TOI=="d13-dilating"),
which(all.data$Recording=="Recording279" & all.data$TOI=="h01-constr"),
which(all.data$Recording=="Recording218" & all.data$TOI=="h09-dilating"),
which(all.data$Recording=="Recording273" & all.data$TOI=="b02-constr"),
which(all.data$Recording=="Recording157" & all.data$TOI=="d04-constr"),
which(all.data$Recording=="Recording166" & all.data$TOI=="d01-constr"),
which(all.data$Recording=="Recording191" & all.data$TOI=="b14-constr"),
which(all.data$Recording=="Recording195" & all.data$TOI=="b09-constr"),
which(all.data$Recording=="Recording197" & all.data$TOI=="h14-constr"),
which(all.data$Recording=="Recording275" & all.data$TOI=="d00-constr"),
which(all.data$Recording=="Recording287" & all.data$TOI=="b10-dilating"),
which(all.data$Recording=="Recording212" & all.data$TOI=="b14-constr"),
which(all.data$Recording=="Recording234" & all.data$TOI=="h15-constr"),
which(all.data$Recording=="Recording294" & all.data$TOI=="b14-dilating"),
which(all.data$Recording=="Recording238" & all.data$TOI=="d08-constr"),
which(all.data$Recording=="Recording206" & all.data$TOI=="h13-dilating"),
which(all.data$Recording=="Recording204" & all.data$TOI=="d04-constr"),
which(all.data$Recording=="Recording224" & all.data$TOI=="h12-constr"),
which(all.data$Recording=="Recording295" & all.data$TOI=="h13-constr"),
which(all.data$Recording=="Recording292" & all.data$TOI=="h14-dilating"),
which(all.data$Recording=="Recording215" & all.data$TOI=="d11-dilating"),
which(all.data$Recording=="Recording230" & all.data$TOI=="b14-dilating"),
which(all.data$Recording=="Recording302" & all.data$TOI=="d08-constr"),
which(all.data$Recording=="Recording330" & all.data$TOI=="b14-constr"),
which(all.data$Recording=="Recording325" & all.data$TOI=="b13-dilating"),
which(all.data$Recording=="Recording322" & all.data$TOI=="d13-dilating"),
which(all.data$Recording=="Recording169" & all.data$TOI=="d05-dilating"),
which(all.data$Recording=="Recording285" & all.data$TOI=="h03-dilating"),
which(all.data$Recording=="Recording286" & all.data$TOI=="d02-constr"),
which(all.data$Recording=="Recording289" & all.data$TOI=="h02-constr"),
which(all.data$Recording=="Recording321" & all.data$TOI=="d12-dilating"),
which(all.data$Recording=="Recording329" & all.data$TOI=="d00-constr"),
which(all.data$Recording=="Recording282" & all.data$TOI=="d13-constr"),
which(all.data$Recording=="Recording342" & all.data$TOI=="b13-constr"),
which(all.data$Recording=="Recording381" & all.data$TOI=="h13-constr"),
which(all.data$Recording=="Recording394" & all.data$TOI=="d12-dilating"), #added this and lines below on
which(all.data$Recording=="Recording367" & all.data$TOI=="h05-dilating"), #10/04
which(all.data$Recording=="Recording392" & all.data$TOI=="b08-dilating"),
which(all.data$Recording=="Recording375" & (all.data$TOI=="d01-dilating" |
all.data$TOI=="b00-dilating")),                                           #until here
which(all.data$Recording=="Recording51" & (all.data$TOI=="d14-constr" |
all.data$TOI=="h07-dilating")),
which(all.data$Recording=="Recording66" & (all.data$TOI=="d01-constr" |
all.data$TOI=="h01-dilating")),
which(all.data$Recording=="Recording88" & (all.data$TOI=="b01-dilating" |
all.data$TOI=="b03-constr")),
which(all.data$Recording=="Recording141" & (all.data$TOI=="b11-constr" |
all.data$TOI=="b10-dilating")),
which(all.data$Recording=="Recording181" & (all.data$TOI=="b02-constr" |
all.data$TOI=="h13-dilating")),
which(all.data$Recording=="Recording303" & (all.data$TOI=="h10-dilating"|
all.data$TOI=="d01-constr")),
which(all.data$Recording=="Recording312" & (all.data$TOI=="b05-dilating"| 
all.data$TOI=="h00-constr")),
which(all.data$Recording=="Recording318" & (all.data$TOI=="h08-dilating" | 
all.data$TOI=="b02-constr")),
which(all.data$Recording=="Recording321" & (all.data$TOI=="d01-dilating"| 
all.data$TOI=="b08-dilating")),
which(all.data$Recording=="Recording322" & (all.data$TOI=="h15-constr" |
all.data$TOI=="h01-constr")),                                              
which(all.data$Recording=="Recording326" & (all.data$TOI=="b11-dilating"| 
all.data$TOI=="h05-constr")),
which(all.data$Recording=="Recording327" & (all.data$TOI=="h06-constr" |
all.data$TOI=="d07-constr")),
which(all.data$Recording=="Recording328" & (all.data$TOI=="b11-constr"| 
all.data$TOI=="d00-dilating")),
which(all.data$Recording=="Recording329" & (all.data$TOI=="b08-constr"| 
all.data$TOI=="h03-constr")),
which(all.data$Recording=="Recording330" & (all.data$TOI=="b09-dilating"| 
all.data$TOI=="b10-dilating")),
which(all.data$Recording=="Recording331" & (all.data$TOI=="d07-dilating"| 
all.data$TOI=="d10-constr")),
which(all.data$Recording=="Recording338" & (all.data$TOI=="d14-dilating"| 
all.data$TOI=="b15-constr")),
which(all.data$Recording=="Recording290" & (all.data$TOI=="h03-constr"| 
all.data$TOI=="d14-constr")),
which(all.data$Recording=="Recording207" & (all.data$TOI=="b08-constr"| 
all.data$TOI=="b11-dilating")),
which(all.data$Recording=="Recording214" & (all.data$TOI=="h06-dilating" | all.data$TOI=="b03-dilating")),
which(all.data$Recording=="Recording227" & (all.data$TOI=="b06-dilating"| all.data$TOI=="h07-dilating")),
which(all.data$Recording=="Recording267" & (all.data$TOI=="h06-dilating" | all.data$TOI=="b03-dilating")),
which(all.data$Recording=="Recording288" & (all.data$TOI=="d10-dilating" | 
all.data$TOI=="b05-constr")),
which(all.data$Recording=="Recording256" & (all.data$TOI=="h09-dilating" | 
all.data$TOI=="h15-dilating"| all.data$TOI=="h09-constr")),
which(all.data$Recording=="Recording254" & (all.data$TOI=="h09-dilating" | 
all.data$TOI=="h09-constr")),
which(all.data$Recording=="Recording218" & (all.data$TOI=="h09-constr" | 
all.data$TOI=="h15-dilating")),
which(all.data$Recording=="Recording246" & all.data$TOI=="h02-dilating"),
which(all.data$Recording=="Recording166" & (all.data$TOI=="b14-dilating" | 
all.data$TOI=="d11-constr")),
which(all.data$Recording=="Recording123" & (all.data$TOI=="b06-constr"| 
all.data$TOI=="d03-dilating")),
which(all.data$Recording=="Recording200" & (all.data$TOI=="b02-dilating"| 
all.data$TOI=="h12-dilating")),
which(all.data$Recording=="Recording253" & all.data$TOI=="d01-constr"),
which(all.data$Recording=="Recording220" & (all.data$TOI=="b05-dilating" | 
all.data$TOI=="h10-dilating")),
which(all.data$Recording=="Recording257" & all.data$TOI=="d12-constr"),
which(all.data$Recording=="Recording255" & (all.data$TOI=="d07-constr" | 
all.data$TOI=="d12-dilating")),
which(all.data$Recording=="Recording219" & all.data$TOI=="h12-constr"),
which(all.data$Recording=="Recording247" & (all.data$TOI=="b02-constr" | 
all.data$TOI=="d03-constr")),
which(all.data$Recording=="Recording304" & (all.data$TOI=="d01-constr"| 
all.data$TOI=="d12-constr")),
which(all.data$Recording=="Recording306" & (all.data$TOI=="d10-constr"| 
all.data$TOI=="h08-constr")),
which(all.data$Recording=="Recording308" & (all.data$TOI=="b05-constr"| 
all.data$TOI=="h06-constr")),
which(all.data$Recording=="Recording339" & (all.data$TOI=="b00-constr"| 
all.data$TOI=="d07-constr")),
which(all.data$Recording=="Recording265" & (all.data$TOI=="d08-dilating" |
all.data$TOI=="b05-constr" | all.data$TOI=="h07-constr")),
which(all.data$Recording=="Recording87" & (all.data$TOI=="b09-constr" |
all.data$TOI=="h13-constr" | all.data$TOI=="h15-constr" | all.data$TOI=="b05-constr")),
which(all.data$Recording=="Recording242" & 
(all.data$TOI=="d04-dilating" | all.data$TOI=="b07-dilating"| all.data$TOI=="d14-constr"| all.data$TOI=="d15-constr"| all.data$TOI=="h05-constr")),
which(all.data$Recording=="Recording241" & 
(all.data$TOI=="b06-dilating" | all.data$TOI=="b15-dilating"| all.data$TOI=="b01-constr"| all.data$TOI=="b12-constr"| all.data$TOI=="h01-dilating")),
which(all.data$Recording=="Recording240" & 
(all.data$TOI=="d02-dilating" | all.data$TOI=="d09-dilating"| all.data$TOI=="h12-constr")),
which(all.data$Recording=="Recording324" & 
(all.data$TOI=="b01-constr" | all.data$TOI=="d05-constr"| all.data$TOI=="h08-constr")),
which(all.data$Recording=="Recording133" & all.data$TOI=="h11-constr"),
which(all.data$Recording=="Recording204" & 
(all.data$TOI=="b13-constr" | 
all.data$TOI=="h08-constr")),
which(all.data$Recording=="Recording243" & all.data$TOI=="d04-constr"),
which(all.data$Recording=="Recording228" & 
(all.data$TOI=="h00-constr" | all.data$TOI=="h10-constr")),
which(all.data$Recording=="Recording229" & all.data$TOI=="h15-constr"),
which((all.data$Recording=="Recording54"| all.data$Recording=="Recording327") & all.data$TOI=="d06-constr"),
which((all.data$Recording=="Recording54"| all.data$Recording=="Recording327") & all.data$TOI=="d06-constr"),
which((all.data$Recording=="Recording279"| all.data$Recording=="Recording322") & all.data$TOI=="h15-constr"),
which((all.data$Recording=="Recording325"| all.data$Recording=="Recording352") & all.data$TOI=="h02-dilating"),
which((all.data$Recording=="Recording325"| all.data$Recording=="Recording323") & all.data$TOI=="b03-constr"),
which((all.data$Recording=="Recording53" | all.data$Recording=="Recording86" | all.data$Recording=="Recording139" | all.data$Recording=="Recording266" | all.data$Recording=="Recording273") & all.data$TOI=="d03-constr"),
which((all.data$Recording=="Recording266"| all.data$Recording=="Recording142"| all.data$Recording=="Recording267") & all.data$TOI=="d13-constr"),
which((all.data$Recording=="Recording338"| all.data$Recording=="Recording342"| all.data$Recording=="Recording192") & all.data$TOI=="h13-constr"),
which((all.data$Recording=="Recording339"| all.data$Recording=="Recording341"| all.data$Recording=="Recording225") & all.data$TOI=="b01-dilating"),
which((all.data$Recording=="Recording94"| all.data$Recording=="Recording149"| all.data$Recording=="Recording92") & 
(all.data$TOI=="h01-constr"| all.data$TOI=="h05-constr")),
which((all.data$Recording=="Recording94"| all.data$Recording=="Recording149"| all.data$Recording=="Recording93") & (all.data$TOI=="b04-dilating" | all.data$TOI=="b12-dilating")),
which((all.data$Recording=="Recording94"| all.data$Recording=="Recording149") & (all.data$TOI=="h03-constr" | all.data$TOI=="d01-constr")),
which((all.data$Recording=="Recording266"| all.data$Recording=="Recording267") & all.data$TOI=="h06-dilating"),
which((all.data$Recording=="Recording148"| all.data$Recording=="Recording266") & all.data$TOI=="h08-constr"),
which((all.data$Recording=="Recording263"| all.data$Recording=="Recording266"| all.data$Recording=="Recording142") & all.data$TOI=="h11-constr"),
which((all.data$Recording=="Recording209" | all.data$Recording=="Recording293"| all.data$Recording=="Recording297") & all.data$TOI=="b08-dilating"),
which((all.data$Recording=="Recording297"| all.data$Recording=="Recording293"| all.data$Recording=="Recording238") & all.data$TOI=="d08-constr"),
which((all.data$Recording=="Recording294"| all.data$Recording=="Recording293"| all.data$Recording=="Recording238") & all.data$TOI=="b14-dilating"),
which((all.data$Recording=="Recording296"| all.data$Recording=="Recording202") & all.data$TOI=="d06-dilating"),
which((all.data$Recording=="Recording296"| all.data$Recording=="Recording136") & all.data$TOI=="b13-dilating"),
which((all.data$Recording=="Recording292"| all.data$Recording=="Recording241") & all.data$TOI=="b06-dilating"),
which((all.data$Recording=="Recording292"| all.data$Recording=="Recording241") & all.data$TOI=="b15-dilating"),
which((all.data$Recording=="Recording298"| all.data$Recording=="Recording292"| all.data$Recording=="Recording241") & all.data$TOI=="b12-constr"),
which(all.data$Recording=="Recording142" & (all.data$TOI=="d02-dilating" | all.data$TOI=="d13-constr"| all.data$TOI=="h11-constr")),
which(all.data$Recording=="Recording263" & (all.data$TOI=="b07-dilating" | all.data$TOI=="b09-dilating"| all.data$TOI=="b11-dilating")),
which(all.data$Recording=="Recording264" & (all.data$TOI=="b01-constr" | 
all.data$TOI=="b04-constr")),
which(all.data$Recording=="Recording261" & (all.data$TOI=="d02-constr" | all.data$TOI=="d12-constr"| all.data$TOI=="h14-dilating"| all.data$TOI=="d14-constr")),
#which(all.data$Recording=="Recording310" & (all.data$TOI=="b00-dilating" | all.data$TOI=="b15-constr"| all.data$TOI=="d14-dilating" | all.data$TOI=="h07-constr" | all.data$TOI=="h13-constr")),
which(all.data$Recording=="Recording133" & (all.data$TOI=="b07-dilating" | all.data$TOI=="d04-dilating"| all.data$TOI=="d15-constr")),
which(all.data$Recording=="Recording146" & (all.data$TOI=="b07-constr" | 
all.data$TOI=="d05-constr")),
which(all.data$Recording=="Recording333" & (all.data$TOI=="d06-dilating" | all.data$TOI=="h08-dilating"| all.data$TOI=="b03-dilating"| all.data$TOI=="h13-dilating")),
which(all.data$Recording=="Recording213" & (all.data$TOI=="b04-constr" | all.data$TOI=="d02-dilating")),
which(all.data$Recording=="Recording216" & (all.data$TOI=="d09-constr" | all.data$TOI=="h01-dilating")),
which(all.data$Recording=="Recording112" & (all.data$TOI=="d04-dilating" | all.data$TOI=="b06-dilating")),
which(all.data$Recording=="Recording73" & (all.data$TOI=="d15-constr" | all.data$TOI=="h02-constr")),
which(all.data$Recording=="Recording111" & (all.data$TOI=="h15-constr" | all.data$TOI=="h14-dilating")),
which(all.data$Recording=="Recording191" & (all.data$TOI=="h07-constr" | all.data$TOI=="b00-dilating")),
which(all.data$Recording=="Recording253" & (all.data$TOI=="b14-dilating" | all.data$TOI=="d11-constr")),
which(all.data$Recording=="Recording276" & (all.data$TOI=="d15-constr" | all.data$TOI=="b12-dilating")),
which(all.data$Recording=="Recording155" & (all.data$TOI=="b08-constr" | all.data$TOI=="h03-constr")),
which(all.data$Recording=="Recording235" & (all.data$TOI=="d10-constr" | all.data$TOI=="h06-dilating")),
which(all.data$Recording=="Recording296" & (all.data$TOI=="b06-dilating" | all.data$TOI=="d06-dilating"| all.data$TOI=="b13-dilating"| all.data$TOI=="h15-constr"| all.data$TOI=="b15-dilating")))


all.data<-all.data %>%  filter(!row_number() %in% trials.to.exclude)
  

all.data.toi<-all.data %>% 
  filter(TOI!="Entire Recording") %>% 
  droplevels() %>% 
  mutate(condition=ifelse(grepl("constr", TOI), "constricting", ifelse(grepl("dilating", TOI), "dilating", "grey_screen")))
```

## Explore data

```{r}
str(all.data.toi)
levels(as.factor(all.data.toi$Recording))
table(all.data.toi$Participant, all.data.toi$Recording)
levels(as.factor(all.data.toi$TOI))
levels(as.factor(all.data.toi$Timeline))

#check how many trials were collected with each dog
all.data.toi.trials<-all.data.toi %>% 
  filter(TOI!="grey_screen") %>% 
#mutate(N_trials_collected=count(Participant)) alternative to what is below
  group_by(Participant) %>% 
  summarise(N_trials_collected=n())
```

##Individual checks to see if there are repeated trials
```{r}
####Kaije
#check how many trials per dog
all.data.toi.trials.kaije<-all.data.toi %>% 
  filter(TOI!="grey_screen") %>% 
  filter(Participant=="kaije") %>% 
  droplevels()
length(all.data.toi.trials.kaije$TOI) 

levels(as.factor(all.data.toi.trials.kaije$TOI)) #which videos did the dog see?
  #mutate(N_trials_collected=count(Participant))
  # group_by(Participant) %>% 
  # summarise(N_trials_collected=n())

all.data.toi.trials.kaije$TOI
#which trials are duplicates?
which(duplicated(all.data.toi.trials.kaije$TOI)==TRUE)

#### Noodle
#check how many trials per dog
all.data.toi.trials.noodle<-all.data.toi %>% 
  filter(TOI!="grey_screen") %>% 
  filter(Participant=="Noodle") %>% 
  droplevels()
length(all.data.toi.trials.noodle$TOI) 

#which videos did the dog see?
levels(as.factor(all.data.toi.trials.noodle$TOI)) 


#### Pepe
#check how many trials per dog
all.data.toi.trials.pepe<-all.data.toi %>% 
  filter(TOI!="grey_screen") %>% 
  filter(Participant=="Pepe") %>% 
  droplevels()
length(all.data.toi.trials.pepe$TOI) 

#which videos did the dog see?
levels(as.factor(all.data.toi.trials.pepe$TOI)) 


#### Barney
#check how many trials per dog
all.data.toi.trials.barney<-all.data.toi %>% 
  filter(TOI!="grey_screen") %>% 
  filter(Participant=="Barney") %>% 
  droplevels()
length(all.data.toi.trials.barney$TOI) 

#which videos did the dog see?
levels(as.factor(all.data.toi.trials.barney$TOI)) 
```

##calculate % tracked (i.e., detected) gaze for each trial. Using the data with the Tobii "Fixation" gaze filter and the Total duration of fixations
```{r}
tracked.gaze.data<-all.data.toi %>% 
  filter(TOI!="grey_screen") %>% 
  mutate(percent_tracked_gaze=(Total_duration_of_fixations/Duration_of_interval)*100) %>% 
  mutate(percent_tracked_glances=(Total_duration_of_Glances/Duration_of_interval)*100)

#using glances instead of fixations results in the gaze being detected for longer
summary(tracked.gaze.data$percent_tracked_gaze)
summary(tracked.gaze.data$percent_tracked_glances)
sum(tracked.gaze.data$percent_tracked_gaze<tracked.gaze.data$percent_tracked_glances)
sum(tracked.gaze.data$percent_tracked_gaze>tracked.gaze.data$percent_tracked_glances)
sum(tracked.gaze.data$percent_tracked_gaze==tracked.gaze.data$percent_tracked_glances)

#potentially replace Total_duration_of_fixations with Total_duration_of_Glances.
#However for now I continue with fixations (the more conservative measure)

#only select relevant columns
tracked.gaze.data.red<-tracked.gaze.data %>% 
  select(c(Recording:Media, Average_pupil_diameter, Total_duration_of_Glances, condition, percent_tracked_gaze, percent_tracked_glances)) %>% 
  droplevels()
  
#Trials to be excluded
##gaze
tracked.gaze.data.red.to.be.excluded<-tracked.gaze.data.red %>% 
group_by(Participant) %>% 
summarise(percent_trials_excluded=sum(percent_tracked_gaze<50)/length(percent_tracked_gaze))

##glances
tracked.glances.data.red.to.be.excluded<-tracked.gaze.data.red %>% 
group_by(Participant) %>% 
summarise(percent_trials_excluded=sum(percent_tracked_glances<50)/length(percent_tracked_glances))
```

##check if there are repeated sessions, to only keep trials with higher % tracked gaze 
```{r}
#Kaije
tracked.gaze.data.red.kaije<-tracked.gaze.data.red %>% 
  filter(Participant=="kaije")
which(duplicated(tracked.gaze.data.red.kaije$TOI)==TRUE)

#Noodle
tracked.gaze.data.red.noodle<-tracked.gaze.data.red %>% 
  filter(Participant=="Noodle")
which(duplicated(tracked.gaze.data.red.noodle$TOI)==TRUE)

#Pepe
tracked.gaze.data.red.pepe<-tracked.gaze.data.red %>% 
  filter(Participant=="Pepe")
which(duplicated(tracked.gaze.data.red.pepe$TOI)==TRUE)

#Messi
tracked.gaze.data.red.messi<-tracked.gaze.data.red %>% 
  filter(Participant=="Messi")
which(duplicated(tracked.gaze.data.red.messi$TOI)==TRUE)

#Barney
tracked.gaze.data.red.barney<-tracked.gaze.data.red %>% 
  filter(Participant=="Barney")
which(duplicated(tracked.gaze.data.red.barney$TOI)==TRUE)

#Jazz
tracked.gaze.data.red.jazz<-tracked.gaze.data.red %>% 
  filter(Participant=="jazz")
which(duplicated(tracked.gaze.data.red.jazz$TOI)==TRUE)
#find out which recordings belong to Jazz, to exclude them from analyses 
sort(unique(tracked.gaze.data.red.jazz$Recording))
```


```{r}
####check which trials should be repeated for each dog

#Barney
to.be.repeated.Barney<-tracked.gaze.data.red %>% 
filter(percent_tracked_gaze<50) %>% 
filter(Participant=="Barney")

#Messi
to.be.repeated.Messi<-tracked.gaze.data.red %>% 
filter(percent_tracked_gaze<50) %>% 
filter(Participant=="Messi")

#Kaije
to.be.repeated.Kaije<-tracked.gaze.data.red %>% 
filter(percent_tracked_gaze<50) %>% 
filter(Participant=="kaije")

#Noodle
to.be.repeated.Noodle<-tracked.gaze.data.red %>% 
filter(percent_tracked_gaze<50) %>% 
filter(Participant=="Noodle")

#Pepe
to.be.repeated.Pepe<-tracked.gaze.data.red %>% 
filter(percent_tracked_gaze<50) %>% 
filter(Participant=="Pepe")

#Jazz
to.be.repeated.Jazz<-tracked.gaze.data.red %>% 
filter(percent_tracked_gaze<50) %>% 
filter(Participant=="jazz")
```

##import the preprocessed pupillometry data 
```{r}
#Tobii gaze fixation and pupil noise reduction filters applied to the data. Then, data pre-processed using the physiodata toolbox, using the default settings. Then data resampled to 1 Hz
#Variable Both_pupil contains resampled pupil size in mm for both eyes
library(readxl)

prepr.pupil.data<-read_excel("./data/PhysioEpochsResampled_10Hz_20240424_human_pupil_parameters.xlsx", skip = 4, col_names=TRUE) %>%  #filter out first 4 rows (before headings)
 separate(Sample_ID, into = c("Physioanalyzer_Period_of_Recording", "Recording", "Time"), sep = " ") %>% 
 mutate(Recording= gsub("\\(Project2_|\\)", "", Recording)) %>% 
 mutate(Time= gsub("\\(", "", Time)) %>% 
 filter(grepl("constr|dilating", epochName))

#add Participant info from Recording name
## Select only the "Recording" and "Participant" columns from tracked.gaze.data (to only keep periods with stimuli video presentation)
tracked.gaze.data.selected <- tracked.gaze.data [, c("Recording", "Participant")]


prepr.pupil.data.merged <-full_join(prepr.pupil.data, tracked.gaze.data.selected) %>%  
  filter(Participant!="jazz") %>% #did not meet inclusion criterion of at least 50% trials with at least 50% tracked gaze
  droplevels() %>% #LL: but here why do I get three values (rows) per 10 Hz? I should only have one row (one pupil size value) for each 10 ms interval
  group_by(Recording) %>% 
  distinct(Time, .keep_all = TRUE) %>% #Keep only the first row for each unique Time value within a recording and all columns
  #LL: I tried these two lines but they do not seem to be doing the right thing as for example in Recording 102 they do not keep all the values of time for the last two stimuli.
  mutate(stim_pupil_movement=ifelse(grepl("constr", epochName), "constricting", "dilating")) %>% 
  mutate(stim_species=ifelse(grepl("DIA_d", Physioanalyzer_Period_of_Recording), "dog", ifelse(grepl("DIA_b", Physioanalyzer_Period_of_Recording), "bonobo", ifelse(grepl("DIA_h", Physioanalyzer_Period_of_Recording), "human","NA"))))
  


levels(as.factor(prepr.pupil.data.merged$Participant))
 
```


